# 数据操作 + 数据预处理

In [ ]:
# part1-1 数据操作

In [1]:
# N维数组是机器学习和神经网络的主要数据结构
# 0-d（标量）~一个类别； 1-d（向量）~一个特征向量； 2-d（矩阵）~一个样本-特征矩阵；
# 3-d~RGB图片（宽*高*通道）；4-d~一个RGB图片批量（批量大学*宽*高*通道）；5-d~一个视频批量（多了一个维度：时间）

In [2]:
# 创建数组
# 所需条件：
# 1. 形状：如 3*4矩阵
# 2. 每个元素的数据类型：如 32位浮点数
# 3. 每个元素的值：如 全是0或随机数

In [3]:
# 访问元素-numpy风格
# 一个元素   [1,2]  表示第1行第2列
# 一行   [1,:]  表示第1行
# 一列   [:,1]  表示第1列
# 子区域   [1:3,1:] 表示行数[1,3)的区间和第1列及以后部分所围成的区域
# 子区域   [::3,::2]  （跳跃式访问） 表示从第0行到最后一行每隔3行访问一次+从第0列到最后一列每隔2列访问一次 所组成的区域

In [4]:
# part1-2 数据操作实现

In [ ]:
import torch
# 导入pytorch

In [9]:
# 张量表示一个数值组成的数组，该数组可能有多个维度
x = torch.arange(12) # 用arange创造一个 行向量x
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
x.shape
# 可以通过张量的 shape 属性来访问张量的 形状和张量中的元素总数

torch.Size([12])

In [15]:
x.numel()
# 如果只想知道元素总数可以用 .numel() 得到的输出值永远是一个标量

12

In [27]:
x = x.reshape(3,4)  #将x改变为一个3行4列的矩阵
x
# 如果要改变一个张量的 形状 而不改变其元素数量和元素值，我们可以调用 reshape 函数
# 除此，我们可以通过-1来调用此自动计算出维度的功能，即 x.reshape(-1,4) x.reshape(3,-1) 上方的式子得到的是一样的

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [33]:
# 可以使用全0，全1，其他常量 或从 特定分布中随机采样的数字
# 全0
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [34]:
# 全1
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [37]:
#随机数——每个元素都从均值为0、标准差为1的标准正态分布中随机取样
torch.rand((2,3,4))

tensor([[[0.5716, 0.5267, 0.5797, 0.2186],
         [0.0116, 0.2758, 0.2162, 0.3686],
         [0.9410, 0.4534, 0.2266, 0.9543]],

        [[0.4029, 0.5563, 0.5821, 0.4607],
         [0.9744, 0.0756, 0.2598, 0.7823],
         [0.8274, 0.4898, 0.5392, 0.4473]]])

In [47]:
# 可以通过提供包含有数值的python列表（或者嵌套列表）来为所需张量中的每个元素赋予确定值
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [63]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2,1]]) # 嵌套列表

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
# 运算符

In [64]:
# 常见的标准算数运算符都可以杯升级为 按元素运算
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y , x-y , x*y , x/y , x**y # **为求幂

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [65]:
# 当然也就能按元素方式应用更多的计算
torch.exp(x)
#除了按元素计算以外，我们也能执行线性代数运算，在后面会讲到

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [66]:
# 我们也可以把多个张量连结在一起，根据dim值不同（维度不同），有不同连结方式：
#【示例中】按行连结（轴-0，即形状的第一个元素）；按列连结（轴-1，即形状的第二个元素）
x = torch.arange(12,dtype = torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim = 0) , torch.cat((x,y),dim = 1) #按行连结 - 3（连接后为3+3行） 和 按列连结 - 4（连结后为4+4列）

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [67]:
# 通过逻辑运算符来构建二元张量 
# 【示例 x==y】在对应位置上，若x==y则为True，反之为False
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [68]:
# 对张量中的所有元素进行求和会产生一个只有一个元素的张量
x.sum()

tensor(66.)

In [69]:
# 广播机制

In [72]:
# 即使形状不同，我们仍然可以通过广播机制来执行按元素操作，执行方式如下：
# 1.通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状
# 2.对生成的数组执行按元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [74]:
a + b
# 广播机制 先将两个向量复制成(3,2)后再进行运算

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [75]:
# 索引和切片

In [78]:
#前者为索引，可以用-1选择最后一个元素，当然-2就是倒数第二个元素
#后者为切片，x[a,b]表示选择[a,b)区间内的元素
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [81]:
#除了读取以外，我们还可以通过指定索引来将元素写入矩阵
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [82]:
#如果要给多个元素赋同一值，我们只需要索引所有的元素，然后为它赋值即可
x[0:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [83]:
# 节省新内存

In [85]:
# 运行一些操作可能会导致为新结果分配内存
before = id(y)
y = y + x
id(y) == before
# id() 函数用于返回对象的唯一标识符，通常词标识符就是该对象在内存中的 地址

False

In [89]:
# 也可以执行原地操作——使用切片表示法将操作的结果分配给先前分配的数组
z = torch.zeros_like(y)
print('id(z):',id(z))
z[:] = z + y
print('id(z):',id(z))

id(z): 2017838076368
id(z): 2017838076368

In [91]:
#如果在后续计算中没有重复使用 x，我们也可以使用 x[:]=x+y 或 x+=y 减少操作的内存开销
before = id(x)
x += y
id(x) == before

True

In [92]:
# 转换为其他python对象

In [98]:
#转换为Numpy张量
import numpy
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [99]:
#将大学为1的张量转换为Python标量
a = torch.tensor([3.5])
a , a.item() , float(a) , int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:
# part2 数据预处理实现

In [108]:
# 读取数据集

In [132]:
#创建一个人工数据集，并储存在csv（逗号分隔值）文件中
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
#该操作是在当前工作目录的上一级创建一个data文件夹，并在其中生成一个house_tiny.csv的小型示例数据集

In [134]:
#常用pandas来读取数据
import pandas as pd

data = pd.read_csv(data_file)
print(data)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [135]:
# 处理缺失值

In [138]:
# 为了处理缺失的数据，典型的方法包括有 插值 和 删除 。
#此处是插值示例
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True)) #这里mean后面的括号内要加上这个条件，否则会有数据类型的报错
#fillna是按列对其填充，其括号中的内容则为填充值（.mean为计算安全均值）
print(inputs)
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [139]:
#对于inputs中的类别值或离散值，我们将“NaN”视为一个类别
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)
inputs

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [140]:
#转换为张量格式

In [145]:
#现在的inputs和outputs中的所有条目都是数值类型，他们就能转换为张量格式
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))